# Generated by Django 3.2.8 on 2022-03-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='企业名')),
                ('detail', models.CharField(max_length=3000, null=True, verbose_name='企业简介')),
                ('applicant', models.IntegerField(default=0, verbose_name='收到简历数')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0, verbose_name='月薪')),
                ('name', models.CharField(max_length=20, verbose_name='职业名')),
                ('application', models.IntegerField(default=0, verbose_name='申请人数')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='需求企业')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.education', verbose_name='学历')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.industry', verbose_name='所属行业')),
            ],
        ),
    ]
