# Generated by Django 3.2.8 on 2022-03-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ImageField(default='RVJ4{7(3T{4`SQ5J90LX2JY.bmp', upload_to='company', verbose_name='公司图片'),
        ),
    ]
