# Generated by Django 3.2.8 on 2022-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='detail',
            field=models.CharField(max_length=5000, null=True, verbose_name='企业简介'),
        ),
    ]
