# Generated by Django 3.2.8 on 2022-03-08 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('detail', models.CharField(max_length=150, verbose_name='评论内容')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.profession', verbose_name='评论的职位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='发表评论的用户')),
            ],
        ),
    ]
