# Generated by Django 3.2.8 on 2022-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('undergraduate', '本科'), ('junior_college', '大专'), ('technical_secondary', '中专'), ('high_school', '初中'), ('higher_school', '高中'), ('primary_school', '小学'), ('no_education', '无学历')], max_length=30, verbose_name='学历')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='行业名')),
                ('work1', models.CharField(max_length=100, null=True, verbose_name='职业名')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.IntegerField(default=0, verbose_name='需求企业数')),
                ('name', models.CharField(default='error', max_length=20, verbose_name='名字')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.industry', verbose_name='所属行业')),
            ],
        ),
    ]
