# Generated by Django 3.2.8 on 2022-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='work1',
            field=models.CharField(max_length=600, null=True, verbose_name='职业名'),
        ),
    ]
