# Generated by Django 3.2.8 on 2022-03-08 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='申请时间')),
                ('action', models.CharField(choices=[('register', '注册'), ('login', '登录')], max_length=10, verbose_name='用途')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.profession', verbose_name='收藏的职位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10, verbose_name='性别')),
                ('major', models.CharField(max_length=15, verbose_name='专业')),
                ('wish_job', models.CharField(max_length=20, verbose_name='期望的工作')),
                ('wish_city', models.CharField(max_length=20, verbose_name='期望的城市')),
                ('wish_salary', models.CharField(max_length=20, verbose_name='期望的薪资')),
                ('identity', models.CharField(choices=[('schooling', '在校生'), ('graduate', '毕业生'), ('working', '职场人士')], max_length=10, verbose_name='身份')),
                ('detail', models.CharField(max_length=200, null=True, verbose_name='个人简介')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.education', verbose_name='学历')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', '简历被接受'), ('failed', '被拒绝'), ('unclear', '结果未出')], max_length=20, verbose_name='简历状态')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.profession', verbose_name='投放简历的职业')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.resume', verbose_name='简历')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
    ]
